# .github/workflows/manual-input.yml
name: Manual Input Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Provide your username'
        required: true
        default: 'Sam'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print User Input
        run: echo "User input: ${{ github.event.inputs.user_input }}"
